@startuml
skinparam ParticipantPadding 1
skinparam SequenceMessagePadding 2
skinparam responseMessageBelowArrow true
hide footbox

participant "SRAM" as sram #c0c0f0
actor "User" as user
participant "Linux host" as linux #c0f0c0

user  ->  linux: start ssh connection
linux --> sram: start pam-weblogin
linux <-- sram: challenge
user <-- linux: show challenge to user
user  ->  sram: open challenge in browser

group SRAM login
  user -> sram: Login
  user <- sram: show code
end

user  ->  linux: enter code

linux --> sram: verify code
linux <- sram: send result, userinfo

linux ->  linux: login as correct user
user o<- linux: shell access

@enduml
